[package]
name = "blaze-exam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.0"
eframe = "0.27.2"
env_logger = "0.11.3"
rfd = "0.14.1"
serde = "1.0.198"
serde_json = "1.0.116"
